//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("USARoadTrip.DataModel", "UserTrips", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(USARoadTrip.Api.EntityModels.UserEntity), "Trip", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(USARoadTrip.Api.EntityModels.TripEntity), true)]
[assembly: EdmRelationshipAttribute("USARoadTrip.DataModel", "TripDestinations", "Trip", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(USARoadTrip.Api.EntityModels.TripEntity), "Location", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(USARoadTrip.Api.EntityModels.LocationEntity))]

#endregion

namespace USARoadTrip.Api.EntityModels
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class USARoadTripContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new USARoadTripContainer object using the connection string found in the 'USARoadTripContainer' section of the application configuration file.
        /// </summary>
        public USARoadTripContainer() : base("name=USARoadTripContainer", "USARoadTripContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new USARoadTripContainer object.
        /// </summary>
        public USARoadTripContainer(string connectionString) : base(connectionString, "USARoadTripContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new USARoadTripContainer object.
        /// </summary>
        public USARoadTripContainer(EntityConnection connection) : base(connection, "USARoadTripContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TripEntity> Trips
        {
            get
            {
                if ((_Trips == null))
                {
                    _Trips = base.CreateObjectSet<TripEntity>("Trips");
                }
                return _Trips;
            }
        }
        private ObjectSet<TripEntity> _Trips;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserEntity> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<UserEntity>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<UserEntity> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LocationEntity> Addresses
        {
            get
            {
                if ((_Addresses == null))
                {
                    _Addresses = base.CreateObjectSet<LocationEntity>("Addresses");
                }
                return _Addresses;
            }
        }
        private ObjectSet<LocationEntity> _Addresses;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Trips EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTrips(TripEntity tripEntity)
        {
            base.AddObject("Trips", tripEntity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(UserEntity userEntity)
        {
            base.AddObject("Users", userEntity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Addresses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAddresses(LocationEntity locationEntity)
        {
            base.AddObject("Addresses", locationEntity);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="USARoadTrip.DataModel", Name="LocationEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LocationEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LocationEntity object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="state">Initial value of the State property.</param>
        /// <param name="zip">Initial value of the Zip property.</param>
        public static LocationEntity CreateLocationEntity(global::System.Int32 id, global::System.String address, global::System.String city, global::System.String state, global::System.String zip)
        {
            LocationEntity locationEntity = new LocationEntity();
            locationEntity.Id = id;
            locationEntity.Address = address;
            locationEntity.City = city;
            locationEntity.State = state;
            locationEntity.Zip = zip;
            return locationEntity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Zip
        {
            get
            {
                return _Zip;
            }
            set
            {
                OnZipChanging(value);
                ReportPropertyChanging("Zip");
                _Zip = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Zip");
                OnZipChanged();
            }
        }
        private global::System.String _Zip;
        partial void OnZipChanging(global::System.String value);
        partial void OnZipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TripOrder
        {
            get
            {
                return _TripOrder;
            }
            set
            {
                OnTripOrderChanging(value);
                ReportPropertyChanging("TripOrder");
                _TripOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TripOrder");
                OnTripOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _TripOrder;
        partial void OnTripOrderChanging(Nullable<global::System.Int32> value);
        partial void OnTripOrderChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="USARoadTrip.DataModel", Name="TripEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TripEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TripEntity object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userNick">Initial value of the UserNick property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static TripEntity CreateTripEntity(global::System.Int32 id, global::System.String userNick, global::System.String name)
        {
            TripEntity tripEntity = new TripEntity();
            tripEntity.Id = id;
            tripEntity.UserNick = userNick;
            tripEntity.Name = name;
            return tripEntity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserNick
        {
            get
            {
                return _UserNick;
            }
            set
            {
                OnUserNickChanging(value);
                ReportPropertyChanging("UserNick");
                _UserNick = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserNick");
                OnUserNickChanged();
            }
        }
        private global::System.String _UserNick;
        partial void OnUserNickChanging(global::System.String value);
        partial void OnUserNickChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("USARoadTrip.DataModel", "UserTrips", "User")]
        public UserEntity User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserEntity>("USARoadTrip.DataModel.UserTrips", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserEntity>("USARoadTrip.DataModel.UserTrips", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserEntity> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserEntity>("USARoadTrip.DataModel.UserTrips", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserEntity>("USARoadTrip.DataModel.UserTrips", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("USARoadTrip.DataModel", "TripDestinations", "Location")]
        public EntityCollection<LocationEntity> Destinations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<LocationEntity>("USARoadTrip.DataModel.TripDestinations", "Location");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<LocationEntity>("USARoadTrip.DataModel.TripDestinations", "Location", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="USARoadTrip.DataModel", Name="UserEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserEntity object.
        /// </summary>
        /// <param name="nick">Initial value of the Nick property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static UserEntity CreateUserEntity(global::System.String nick, global::System.String password)
        {
            UserEntity userEntity = new UserEntity();
            userEntity.Nick = nick;
            userEntity.Password = password;
            return userEntity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nick
        {
            get
            {
                return _Nick;
            }
            set
            {
                if (_Nick != value)
                {
                    OnNickChanging(value);
                    ReportPropertyChanging("Nick");
                    _Nick = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Nick");
                    OnNickChanged();
                }
            }
        }
        private global::System.String _Nick;
        partial void OnNickChanging(global::System.String value);
        partial void OnNickChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("USARoadTrip.DataModel", "UserTrips", "Trip")]
        public EntityCollection<TripEntity> Trips
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TripEntity>("USARoadTrip.DataModel.UserTrips", "Trip");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TripEntity>("USARoadTrip.DataModel.UserTrips", "Trip", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
